name: Deploy home.html to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5  # ✅ latest

      - name: Upload site files
        uses: actions/upload-pages-artifact@v3  # ✅ latest and safe
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # ✅ latest
